export * from "./accordion/Accordion.component";
export * from "./breadcrumb/Breadcrumb.component";
export * from "./button/Button.component";
export * from "./card/AlertCard.component";
export * from "./card/Card.component";
export * from "./card/DashboardCard.component";
export * from "./card/GalleryCard.component";
export * from "./card/ProductCard.component";
export * from "./card/ProfileCard.component";
export * from "./carousel/Carousel.component";
export * from "./chip/Chip.component";
export * from "./input/Checkbox.component";
export * from "./input/Input.component";
export * from "./input/InputCheckbox.component";
export * from "./input/InputCurrency.component";
export * from "./input/InputDate.component";
export * from "./input/InputDatetime.component";
export * from "./input/InputDocument.component";
export * from "./input/InputImage.component";
export * from "./input/InputNumber.component";
export * from "./input/InputOtp.component";
export * from "./input/InputPassword.component";
export * from "./input/InputRadio.component";
export * from "./input/InputTime.component";
export * from "./input/InputValues.component";
export * from "./input/Radio.component";
export * from "./input/Select.component";
export * from "./modal/BottomSheet.component";
export * from "./modal/FloatingPage.component";
export * from "./modal/Modal.component";
export * from "./modal/ModalConfirm.component";
export * from "./modal/Toast.component";
export * from "./nav/Bottombar.component";
export * from "./nav/Footer.component";
export * from "./nav/Headbar.component";
export * from "./nav/Navbar.component";
export * from "./nav/Sidebar.component";
export * from "./nav/Tabbar.component";
export * from "./nav/Wizard.component";
export * from "./supervision/FormSupervision.component";
export * from "./supervision/TableSupervision.component";
export * from "./table/ControlBar.component";
export * from "./table/FilterComponent";
export * from "./table/Pagination.component";
export * from "./table/Table.component";
export * from "./typography/TypographyArticle.component";
export * from "./typography/TypographyColumn.component";
export * from "./typography/TypographyContent.component";
export * from "./typography/TypographyTips.component";
export * from "./wrap/Draggable.component";
export * from "./wrap/Image.component";
export * from "./wrap/OutsideClick.component";
export * from "./wrap/ScrollContainer.component";
export * from "./wrap/ShortcutProvider";
export * from "./wrap/Swipe.component";

import { registry } from "@utils";
import { TableComponent } from "./table/Table.component.js";
import { ButtonComponent } from "./button/Button.component.js";
import { SelectComponent } from "./input/Select.component.js";
import { ModalComponent } from "./modal/Modal.component.js";
import { FilterComponent } from "./table/FilterComponent.js";
import { useToggleContext } from "@contexts";

registry.register("TableComponent", TableComponent);
registry.register("ButtonComponent", ButtonComponent);
registry.register("SelectComponent", SelectComponent);
registry.register("ModalComponent", ModalComponent);
registry.register("FilterComponent", FilterComponent);
registry.register("useToggleContext", useToggleContext);
